/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const snapshot = [
    {
      "createRule": null,
      "deleteRule": null,
      "fields": [
        {
          "autogeneratePattern": "[a-z0-9]{15}",
          "help": "",
          "hidden": false,
          "id": "text3208210256",
          "max": 15,
          "min": 15,
          "name": "id",
          "pattern": "^[a-z0-9]+$",
          "presentable": false,
          "primaryKey": true,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text455797646",
          "max": 0,
          "min": 0,
          "name": "collectionRef",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text127846527",
          "max": 0,
          "min": 0,
          "name": "recordRef",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text1582905952",
          "max": 0,
          "min": 0,
          "name": "method",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "hidden": false,
          "id": "autodate2990389176",
          "name": "created",
          "onCreate": true,
          "onUpdate": false,
          "presentable": false,
          "system": true,
          "type": "autodate"
        },
        {
          "hidden": false,
          "id": "autodate3332085495",
          "name": "updated",
          "onCreate": true,
          "onUpdate": true,
          "presentable": false,
          "system": true,
          "type": "autodate"
        }
      ],
      "id": "pbc_2279338944",
      "indexes": [
        "CREATE INDEX `idx_mfas_collectionRef_recordRef` ON `_mfas` (collectionRef,recordRef)"
      ],
      "listRule": "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
      "name": "_mfas",
      "system": true,
      "type": "base",
      "updateRule": null,
      "viewRule": "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId"
    },
    {
      "createRule": null,
      "deleteRule": null,
      "fields": [
        {
          "autogeneratePattern": "[a-z0-9]{15}",
          "help": "",
          "hidden": false,
          "id": "text3208210256",
          "max": 15,
          "min": 15,
          "name": "id",
          "pattern": "^[a-z0-9]+$",
          "presentable": false,
          "primaryKey": true,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text455797646",
          "max": 0,
          "min": 0,
          "name": "collectionRef",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text127846527",
          "max": 0,
          "min": 0,
          "name": "recordRef",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "cost": 8,
          "help": "",
          "hidden": true,
          "id": "password901924565",
          "max": 0,
          "min": 0,
          "name": "password",
          "pattern": "",
          "presentable": false,
          "required": true,
          "system": true,
          "type": "password"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": true,
          "id": "text3866985172",
          "max": 0,
          "min": 0,
          "name": "sentTo",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": true,
          "type": "text"
        },
        {
          "hidden": false,
          "id": "autodate2990389176",
          "name": "created",
          "onCreate": true,
          "onUpdate": false,
          "presentable": false,
          "system": true,
          "type": "autodate"
        },
        {
          "hidden": false,
          "id": "autodate3332085495",
          "name": "updated",
          "onCreate": true,
          "onUpdate": true,
          "presentable": false,
          "system": true,
          "type": "autodate"
        }
      ],
      "id": "pbc_1638494021",
      "indexes": [
        "CREATE INDEX `idx_otps_collectionRef_recordRef` ON `_otps` (collectionRef, recordRef)"
      ],
      "listRule": "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
      "name": "_otps",
      "system": true,
      "type": "base",
      "updateRule": null,
      "viewRule": "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId"
    },
    {
      "createRule": null,
      "deleteRule": "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
      "fields": [
        {
          "autogeneratePattern": "[a-z0-9]{15}",
          "help": "",
          "hidden": false,
          "id": "text3208210256",
          "max": 15,
          "min": 15,
          "name": "id",
          "pattern": "^[a-z0-9]+$",
          "presentable": false,
          "primaryKey": true,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text455797646",
          "max": 0,
          "min": 0,
          "name": "collectionRef",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text127846527",
          "max": 0,
          "min": 0,
          "name": "recordRef",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text2462348188",
          "max": 0,
          "min": 0,
          "name": "provider",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text1044722854",
          "max": 0,
          "min": 0,
          "name": "providerId",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "hidden": false,
          "id": "autodate2990389176",
          "name": "created",
          "onCreate": true,
          "onUpdate": false,
          "presentable": false,
          "system": true,
          "type": "autodate"
        },
        {
          "hidden": false,
          "id": "autodate3332085495",
          "name": "updated",
          "onCreate": true,
          "onUpdate": true,
          "presentable": false,
          "system": true,
          "type": "autodate"
        }
      ],
      "id": "pbc_2281828961",
      "indexes": [
        "CREATE UNIQUE INDEX `idx_externalAuths_record_provider` ON `_externalAuths` (collectionRef, recordRef, provider)",
        "CREATE UNIQUE INDEX `idx_externalAuths_collection_provider` ON `_externalAuths` (collectionRef, provider, providerId)"
      ],
      "listRule": "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
      "name": "_externalAuths",
      "system": true,
      "type": "base",
      "updateRule": null,
      "viewRule": "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId"
    },
    {
      "createRule": null,
      "deleteRule": "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
      "fields": [
        {
          "autogeneratePattern": "[a-z0-9]{15}",
          "help": "",
          "hidden": false,
          "id": "text3208210256",
          "max": 15,
          "min": 15,
          "name": "id",
          "pattern": "^[a-z0-9]+$",
          "presentable": false,
          "primaryKey": true,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text455797646",
          "max": 0,
          "min": 0,
          "name": "collectionRef",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text127846527",
          "max": 0,
          "min": 0,
          "name": "recordRef",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text4228609354",
          "max": 0,
          "min": 0,
          "name": "fingerprint",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "hidden": false,
          "id": "autodate2990389176",
          "name": "created",
          "onCreate": true,
          "onUpdate": false,
          "presentable": false,
          "system": true,
          "type": "autodate"
        },
        {
          "hidden": false,
          "id": "autodate3332085495",
          "name": "updated",
          "onCreate": true,
          "onUpdate": true,
          "presentable": false,
          "system": true,
          "type": "autodate"
        }
      ],
      "id": "pbc_4275539003",
      "indexes": [
        "CREATE UNIQUE INDEX `idx_authOrigins_unique_pairs` ON `_authOrigins` (collectionRef, recordRef, fingerprint)"
      ],
      "listRule": "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId",
      "name": "_authOrigins",
      "system": true,
      "type": "base",
      "updateRule": null,
      "viewRule": "@request.auth.id != '' && recordRef = @request.auth.id && collectionRef = @request.auth.collectionId"
    },
    {
      "authAlert": {
        "emailTemplate": {
          "body": "<p>Hello,</p>\n<p>We noticed a login to your {APP_NAME} account from a new location:</p>\n<p><em>{ALERT_INFO}</em></p>\n<p><strong>If this wasn't you, you should immediately change your {APP_NAME} account password to revoke access from all other locations.</strong></p>\n<p>If this was you, you may disregard this email.</p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
          "subject": "Login from a new location"
        },
        "enabled": false
      },
      "authRule": "",
      "authToken": {
        "duration": 86400
      },
      "confirmEmailChangeTemplate": {
        "body": "<p>Hello,</p>\n<p>Click on the button below to confirm your new email address.</p>\n<p>\n  <a class=\"btn\" href=\"{APP_URL}/_/#/auth/confirm-email-change/{TOKEN}\" target=\"_blank\" rel=\"noopener\">Confirm new email</a>\n</p>\n<p><i>If you didn't ask to change your email address, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
        "subject": "Confirm your {APP_NAME} new email address"
      },
      "createRule": null,
      "deleteRule": null,
      "emailChangeToken": {
        "duration": 1800
      },
      "fields": [
        {
          "autogeneratePattern": "[a-z0-9]{15}",
          "help": "",
          "hidden": false,
          "id": "text3208210256",
          "max": 15,
          "min": 15,
          "name": "id",
          "pattern": "^[a-z0-9]+$",
          "presentable": false,
          "primaryKey": true,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "cost": 0,
          "help": "",
          "hidden": true,
          "id": "password901924565",
          "max": 0,
          "min": 8,
          "name": "password",
          "pattern": "",
          "presentable": false,
          "required": true,
          "system": true,
          "type": "password"
        },
        {
          "autogeneratePattern": "[a-zA-Z0-9]{50}",
          "help": "",
          "hidden": true,
          "id": "text2504183744",
          "max": 60,
          "min": 30,
          "name": "tokenKey",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "exceptDomains": null,
          "help": "",
          "hidden": false,
          "id": "email3885137012",
          "name": "email",
          "onlyDomains": null,
          "presentable": false,
          "required": true,
          "system": true,
          "type": "email"
        },
        {
          "help": "",
          "hidden": false,
          "id": "bool1547992806",
          "name": "emailVisibility",
          "presentable": false,
          "required": false,
          "system": true,
          "type": "bool"
        },
        {
          "help": "",
          "hidden": false,
          "id": "bool256245529",
          "name": "verified",
          "presentable": false,
          "required": false,
          "system": true,
          "type": "bool"
        },
        {
          "hidden": false,
          "id": "autodate2990389176",
          "name": "created",
          "onCreate": true,
          "onUpdate": false,
          "presentable": false,
          "system": true,
          "type": "autodate"
        },
        {
          "hidden": false,
          "id": "autodate3332085495",
          "name": "updated",
          "onCreate": true,
          "onUpdate": true,
          "presentable": false,
          "system": true,
          "type": "autodate"
        }
      ],
      "fileToken": {
        "duration": 180
      },
      "id": "pbc_3142635823",
      "indexes": [
        "CREATE UNIQUE INDEX `idx_tokenKey_pbc_3142635823` ON `_superusers` (`tokenKey`)",
        "CREATE UNIQUE INDEX `idx_email_pbc_3142635823` ON `_superusers` (`email`) WHERE `email` != ''"
      ],
      "listRule": null,
      "manageRule": null,
      "mfa": {
        "duration": 600,
        "enabled": false,
        "rule": ""
      },
      "name": "_superusers",
      "oauth2": {
        "enabled": false,
        "mappedFields": {
          "avatarURL": "",
          "id": "",
          "name": "",
          "username": ""
        }
      },
      "otp": {
        "duration": 180,
        "emailTemplate": {
          "body": "<p>Hello,</p>\n<p>Your one-time password is: <strong>{OTP}</strong></p>\n<p><i>If you didn't ask for the one-time password, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
          "subject": "OTP for {APP_NAME}"
        },
        "enabled": false,
        "length": 8
      },
      "passwordAuth": {
        "enabled": true,
        "identityFields": [
          "email"
        ]
      },
      "passwordResetToken": {
        "duration": 1800
      },
      "resetPasswordTemplate": {
        "body": "<p>Hello,</p>\n<p>Click on the button below to reset your password.</p>\n<p>\n  <a class=\"btn\" href=\"{APP_URL}/_/#/auth/confirm-password-reset/{TOKEN}\" target=\"_blank\" rel=\"noopener\">Reset password</a>\n</p>\n<p><i>If you didn't ask to reset your password, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
        "subject": "Reset your {APP_NAME} password"
      },
      "system": true,
      "type": "auth",
      "updateRule": null,
      "verificationTemplate": {
        "body": "<p>Hello,</p>\n<p>Thank you for joining us at {APP_NAME}.</p>\n<p>Click on the button below to verify your email address.</p>\n<p>\n  <a class=\"btn\" href=\"{APP_URL}/_/#/auth/confirm-verification/{TOKEN}\" target=\"_blank\" rel=\"noopener\">Verify</a>\n</p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
        "subject": "Verify your {APP_NAME} email"
      },
      "verificationToken": {
        "duration": 259200
      },
      "viewRule": null
    },
    {
      "authAlert": {
        "emailTemplate": {
          "body": "<p>Hello,</p>\n<p>We noticed a login to your {APP_NAME} account from a new location:</p>\n<p><em>{ALERT_INFO}</em></p>\n<p><strong>If this wasn't you, you should immediately change your {APP_NAME} account password to revoke access from all other locations.</strong></p>\n<p>If this was you, you may disregard this email.</p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
          "subject": "Login from a new location"
        },
        "enabled": false
      },
      "authRule": "",
      "authToken": {
        "duration": 604800
      },
      "confirmEmailChangeTemplate": {
        "body": "<p>Hello,</p>\n<p>Click on the button below to confirm your new email address.</p>\n<p>\n  <a class=\"btn\" href=\"{APP_URL}/_/#/auth/confirm-email-change/{TOKEN}\" target=\"_blank\" rel=\"noopener\">Confirm new email</a>\n</p>\n<p><i>If you didn't ask to change your email address, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
        "subject": "Confirm your {APP_NAME} new email address"
      },
      "createRule": "@request.auth.id != '' && @request.auth.role = 'Superadmin'",
      "deleteRule": "@request.auth.id != '' && @request.auth.role = 'Superadmin'",
      "emailChangeToken": {
        "duration": 1800
      },
      "fields": [
        {
          "autogeneratePattern": "[a-z0-9]{15}",
          "help": "",
          "hidden": false,
          "id": "text3208210256",
          "max": 15,
          "min": 15,
          "name": "id",
          "pattern": "^[a-z0-9]+$",
          "presentable": false,
          "primaryKey": true,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "help": "",
          "hidden": false,
          "id": "select7063221283",
          "maxSelect": 1,
          "name": "role",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "select",
          "values": [
            "Superadmin",
            "Administrador",
            "Contabilidad",
            "Recepcion",
            "Despachador"
          ]
        },
        {
          "cost": 0,
          "help": "",
          "hidden": true,
          "id": "password901924565",
          "max": 0,
          "min": 8,
          "name": "password",
          "pattern": "",
          "presentable": false,
          "required": true,
          "system": true,
          "type": "password"
        },
        {
          "autogeneratePattern": "[a-zA-Z0-9]{50}",
          "help": "",
          "hidden": true,
          "id": "text2504183744",
          "max": 60,
          "min": 30,
          "name": "tokenKey",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "exceptDomains": null,
          "help": "",
          "hidden": false,
          "id": "email3885137012",
          "name": "email",
          "onlyDomains": null,
          "presentable": false,
          "required": true,
          "system": true,
          "type": "email"
        },
        {
          "help": "",
          "hidden": false,
          "id": "bool1547992806",
          "name": "emailVisibility",
          "presentable": false,
          "required": false,
          "system": true,
          "type": "bool"
        },
        {
          "help": "",
          "hidden": false,
          "id": "bool256245529",
          "name": "verified",
          "presentable": false,
          "required": false,
          "system": true,
          "type": "bool"
        }
      ],
      "fileToken": {
        "duration": 180
      },
      "id": "pbc_1736455494",
      "indexes": [
        "CREATE UNIQUE INDEX `idx_tokenKey_pbc_1736455494` ON `users` (`tokenKey`)",
        "CREATE UNIQUE INDEX `idx_email_pbc_1736455494` ON `users` (`email`) WHERE `email` != ''"
      ],
      "listRule": "@request.auth.id != '' && (@request.auth.role = 'Superadmin' || @request.auth.role = 'Administrador')",
      "manageRule": null,
      "mfa": {
        "duration": 600,
        "enabled": false,
        "rule": ""
      },
      "name": "users",
      "oauth2": {
        "enabled": false,
        "mappedFields": {
          "avatarURL": "",
          "id": "",
          "name": "",
          "username": ""
        }
      },
      "otp": {
        "duration": 180,
        "emailTemplate": {
          "body": "<p>Hello,</p>\n<p>Your one-time password is: <strong>{OTP}</strong></p>\n<p><i>If you didn't ask for the one-time password, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
          "subject": "OTP for {APP_NAME}"
        },
        "enabled": false,
        "length": 8
      },
      "passwordAuth": {
        "enabled": true,
        "identityFields": [
          "email"
        ]
      },
      "passwordResetToken": {
        "duration": 1800
      },
      "resetPasswordTemplate": {
        "body": "<p>Hello,</p>\n<p>Click on the button below to reset your password.</p>\n<p>\n  <a class=\"btn\" href=\"{APP_URL}/_/#/auth/confirm-password-reset/{TOKEN}\" target=\"_blank\" rel=\"noopener\">Reset password</a>\n</p>\n<p><i>If you didn't ask to reset your password, you can ignore this email.</i></p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
        "subject": "Reset your {APP_NAME} password"
      },
      "system": false,
      "type": "auth",
      "updateRule": "@request.auth.id != '' && (@request.auth.role = 'Superadmin' || (@request.auth.id = id && @request.auth.role = 'Administrador'))",
      "verificationTemplate": {
        "body": "<p>Hello,</p>\n<p>Thank you for joining us at {APP_NAME}.</p>\n<p>Click on the button below to verify your email address.</p>\n<p>\n  <a class=\"btn\" href=\"{APP_URL}/_/#/auth/confirm-verification/{TOKEN}\" target=\"_blank\" rel=\"noopener\">Verify</a>\n</p>\n<p>\n  Thanks,<br/>\n  {APP_NAME} team\n</p>",
        "subject": "Verify your {APP_NAME} email"
      },
      "verificationToken": {
        "duration": 259200
      },
      "viewRule": "@request.auth.id = id || (@request.auth.id != '' && (@request.auth.role = 'Superadmin' || @request.auth.role = 'Administrador'))"
    },
    {
      "createRule": "@request.auth.role = 'Superadmin' || @request.auth.role = 'Administrador'",
      "deleteRule": "@request.auth.role = 'Superadmin'",
      "fields": [
        {
          "autogeneratePattern": "[a-z0-9]{15}",
          "help": "",
          "hidden": false,
          "id": "text2146774566",
          "max": 15,
          "min": 15,
          "name": "id",
          "pattern": "^[a-z0-9]+$",
          "presentable": false,
          "primaryKey": true,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text1963737756",
          "max": 0,
          "min": 0,
          "name": "nombre",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": false,
          "type": "text"
        },
        {
          "hidden": false,
          "id": "autodate1423480039",
          "name": "created",
          "onCreate": true,
          "onUpdate": false,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "hidden": false,
          "id": "autodate6885993858",
          "name": "updated",
          "onCreate": true,
          "onUpdate": true,
          "presentable": false,
          "system": false,
          "type": "autodate"
        }
      ],
      "id": "pbc_3586547091",
      "indexes": [],
      "listRule": "",
      "name": "zonas",
      "system": false,
      "type": "base",
      "updateRule": "@request.auth.role = 'Superadmin' || @request.auth.role = 'Administrador'",
      "viewRule": ""
    },
    {
      "createRule": "@request.auth.id != ''",
      "deleteRule": "@request.auth.id != ''",
      "fields": [
        {
          "autogeneratePattern": "[a-z0-9]{15}",
          "help": "",
          "hidden": false,
          "id": "text2265266821",
          "max": 15,
          "min": 15,
          "name": "id",
          "pattern": "^[a-z0-9]+$",
          "presentable": false,
          "primaryKey": true,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text3704998681",
          "max": 0,
          "min": 0,
          "name": "descripcion",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "hidden": false,
          "id": "autodate9985375749",
          "name": "created",
          "onCreate": true,
          "onUpdate": false,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "hidden": false,
          "id": "autodate3117070633",
          "name": "updated",
          "onCreate": true,
          "onUpdate": true,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "help": "",
          "hidden": false,
          "id": "number3904593951",
          "max": null,
          "min": null,
          "name": "monto_total",
          "onlyInt": false,
          "presentable": false,
          "required": false,
          "system": false,
          "type": "number"
        },
        {
          "help": "",
          "hidden": false,
          "id": "number971067359",
          "max": null,
          "min": null,
          "name": "costo_unitario",
          "onlyInt": false,
          "presentable": false,
          "required": false,
          "system": false,
          "type": "number"
        },
        {
          "help": "",
          "hidden": false,
          "id": "date27834329",
          "max": "",
          "min": "",
          "name": "fecha",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "date"
        }
      ],
      "id": "pbc_1523352486",
      "indexes": [],
      "listRule": "",
      "name": "ventas",
      "system": false,
      "type": "base",
      "updateRule": "@request.auth.id != ''",
      "viewRule": ""
    },
    {
      "createRule": "@request.auth.id != ''",
      "deleteRule": "@request.auth.id != ''",
      "fields": [
        {
          "autogeneratePattern": "[a-z0-9]{15}",
          "help": "",
          "hidden": false,
          "id": "text3035548077",
          "max": 15,
          "min": 15,
          "name": "id",
          "pattern": "^[a-z0-9]+$",
          "presentable": false,
          "primaryKey": true,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text3985028822",
          "max": 0,
          "min": 0,
          "name": "nombre",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": false,
          "type": "text"
        },
        {
          "exceptDomains": [],
          "help": "",
          "hidden": false,
          "id": "email1392218220",
          "name": "email",
          "onlyDomains": [],
          "presentable": false,
          "required": false,
          "system": false,
          "type": "email"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text0381251297",
          "max": 0,
          "min": 0,
          "name": "telefono",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "hidden": false,
          "id": "autodate8261410231",
          "name": "created",
          "onCreate": true,
          "onUpdate": false,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "hidden": false,
          "id": "autodate4743972799",
          "name": "updated",
          "onCreate": true,
          "onUpdate": true,
          "presentable": false,
          "system": false,
          "type": "autodate"
        }
      ],
      "id": "pbc_8236498715",
      "indexes": [],
      "listRule": "",
      "name": "clientes",
      "system": false,
      "type": "base",
      "updateRule": "@request.auth.id != ''",
      "viewRule": ""
    },
    {
      "createRule": "@request.auth.role = 'Superadmin' || @request.auth.role = 'Administrador' || @request.auth.role = 'Contabilidad' || @request.auth.role = 'Recepcion'",
      "deleteRule": "@request.auth.role = 'Superadmin'",
      "fields": [
        {
          "autogeneratePattern": "[a-z0-9]{15}",
          "help": "",
          "hidden": false,
          "id": "text6465453343",
          "max": 15,
          "min": 15,
          "name": "id",
          "pattern": "^[a-z0-9]+$",
          "presentable": false,
          "primaryKey": true,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "cascadeDelete": false,
          "collectionId": "pbc_8236498715",
          "help": "",
          "hidden": false,
          "id": "relation7137067335",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "cliente",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "relation"
        },
        {
          "help": "",
          "hidden": false,
          "id": "date3510045714",
          "max": "",
          "min": "",
          "name": "fecha_ultima_compra",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "date"
        },
        {
          "help": "",
          "hidden": false,
          "id": "number0577172146",
          "max": null,
          "min": 0,
          "name": "dias_sin_comprar",
          "onlyInt": false,
          "presentable": false,
          "required": true,
          "system": false,
          "type": "number"
        },
        {
          "help": "",
          "hidden": false,
          "id": "date2856498696",
          "max": "",
          "min": "",
          "name": "fecha_proximo_recordatorio",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "date"
        },
        {
          "help": "",
          "hidden": false,
          "id": "select9736676759",
          "maxSelect": 1,
          "name": "estatus",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "select",
          "values": [
            "pendiente",
            "completado",
            "cancelado"
          ]
        },
        {
          "cascadeDelete": false,
          "collectionId": "pbc_1736455494",
          "help": "",
          "hidden": false,
          "id": "relation0167020611",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "creado_por",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "relation"
        },
        {
          "hidden": false,
          "id": "autodate8736786302",
          "name": "fecha_creacion",
          "onCreate": true,
          "onUpdate": false,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text1216368207",
          "max": 0,
          "min": 0,
          "name": "notas",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "hidden": false,
          "id": "autodate9274074860",
          "name": "created",
          "onCreate": true,
          "onUpdate": false,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "hidden": false,
          "id": "autodate2328832598",
          "name": "updated",
          "onCreate": true,
          "onUpdate": true,
          "presentable": false,
          "system": false,
          "type": "autodate"
        }
      ],
      "id": "pbc_4816188337",
      "indexes": [],
      "listRule": "@request.auth.id != ''",
      "name": "recordatorios_clientes",
      "system": false,
      "type": "base",
      "updateRule": "@request.auth.role = 'Superadmin' || @request.auth.role = 'Administrador' || creado_por = @request.auth.id",
      "viewRule": "@request.auth.id != ''"
    },
    {
      "createRule": "@request.auth.id != ''",
      "deleteRule": "usuario_destino = @request.auth.id",
      "fields": [
        {
          "autogeneratePattern": "[a-z0-9]{15}",
          "help": "",
          "hidden": false,
          "id": "text6098033804",
          "max": 15,
          "min": 15,
          "name": "id",
          "pattern": "^[a-z0-9]+$",
          "presentable": false,
          "primaryKey": true,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "help": "",
          "hidden": false,
          "id": "select1335631028",
          "maxSelect": 1,
          "name": "tipo",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "select",
          "values": [
            "cambio_estatus",
            "recordatorio",
            "sistema"
          ]
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text9445510879",
          "max": 0,
          "min": 0,
          "name": "mensaje",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": false,
          "type": "text"
        },
        {
          "cascadeDelete": false,
          "collectionId": "pbc_1736455494",
          "help": "",
          "hidden": false,
          "id": "relation6077469031",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "usuario_destino",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "relation"
        },
        {
          "help": "",
          "hidden": false,
          "id": "bool9101491353",
          "name": "leida",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "bool"
        },
        {
          "hidden": false,
          "id": "autodate0160322526",
          "name": "fecha_creacion",
          "onCreate": true,
          "onUpdate": false,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "cascadeDelete": false,
          "collectionId": "pbc_1523352486",
          "help": "",
          "hidden": false,
          "id": "relation1557727824",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "venta_relacionada",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "relation"
        },
        {
          "cascadeDelete": false,
          "collectionId": "pbc_4816188337",
          "help": "",
          "hidden": false,
          "id": "relation5332520301",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "recordatorio_relacionado",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "relation"
        },
        {
          "hidden": false,
          "id": "autodate2608659186",
          "name": "created",
          "onCreate": true,
          "onUpdate": false,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "hidden": false,
          "id": "autodate0540066294",
          "name": "updated",
          "onCreate": true,
          "onUpdate": true,
          "presentable": false,
          "system": false,
          "type": "autodate"
        }
      ],
      "id": "pbc_5911155507",
      "indexes": [],
      "listRule": "usuario_destino = @request.auth.id",
      "name": "notificaciones",
      "system": false,
      "type": "base",
      "updateRule": "usuario_destino = @request.auth.id",
      "viewRule": "usuario_destino = @request.auth.id"
    },
    {
      "createRule": "@request.auth.id != ''",
      "deleteRule": "@request.auth.role = 'Superadmin'",
      "fields": [
        {
          "autogeneratePattern": "[a-z0-9]{15}",
          "help": "",
          "hidden": false,
          "id": "text4263733321",
          "max": 15,
          "min": 15,
          "name": "id",
          "pattern": "^[a-z0-9]+$",
          "presentable": false,
          "primaryKey": true,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "help": "",
          "hidden": false,
          "id": "select2666136487",
          "maxSelect": 1,
          "name": "tipo_actividad",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "select",
          "values": [
            "creacion_venta",
            "cambio_estatus_venta",
            "creacion_recordatorio",
            "cambio_costo",
            "cambio_logotipo"
          ]
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text6914090609",
          "max": 0,
          "min": 0,
          "name": "descripcion",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": false,
          "type": "text"
        },
        {
          "cascadeDelete": false,
          "collectionId": "pbc_1736455494",
          "help": "",
          "hidden": false,
          "id": "relation3519820482",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "usuario",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "relation"
        },
        {
          "hidden": false,
          "id": "autodate0684784591",
          "name": "fecha",
          "onCreate": true,
          "onUpdate": false,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text5455383034",
          "max": 0,
          "min": 0,
          "name": "entidad_relacionada",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text4484927701",
          "max": 0,
          "min": 0,
          "name": "detalles_json",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "hidden": false,
          "id": "autodate5129181506",
          "name": "created",
          "onCreate": true,
          "onUpdate": false,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "hidden": false,
          "id": "autodate0297688449",
          "name": "updated",
          "onCreate": true,
          "onUpdate": true,
          "presentable": false,
          "system": false,
          "type": "autodate"
        }
      ],
      "id": "pbc_3889136580",
      "indexes": [],
      "listRule": "@request.auth.id != ''",
      "name": "historial_actividades",
      "system": false,
      "type": "base",
      "updateRule": null,
      "viewRule": "@request.auth.id != ''"
    },
    {
      "createRule": "@request.auth.role = 'Superadmin'",
      "deleteRule": "@request.auth.role = 'Superadmin'",
      "fields": [
        {
          "autogeneratePattern": "[a-z0-9]{15}",
          "help": "",
          "hidden": false,
          "id": "text1786958514",
          "max": 15,
          "min": 15,
          "name": "id",
          "pattern": "^[a-z0-9]+$",
          "presentable": false,
          "primaryKey": true,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text9900853224",
          "max": 0,
          "min": 0,
          "name": "nombre_empresa",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "help": "",
          "hidden": false,
          "id": "file1525749832",
          "maxSelect": 1,
          "maxSize": 2097152,
          "mimeTypes": [
            "image/png",
            "image/jpeg",
            "image/svg+xml"
          ],
          "name": "logo_url",
          "presentable": false,
          "protected": false,
          "required": false,
          "system": false,
          "thumbs": [],
          "type": "file"
        },
        {
          "hidden": false,
          "id": "autodate6324752607",
          "name": "fecha_actualizacion",
          "onCreate": true,
          "onUpdate": true,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "cascadeDelete": false,
          "collectionId": "pbc_1736455494",
          "help": "",
          "hidden": false,
          "id": "relation0278341900",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "actualizado_por",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "relation"
        },
        {
          "hidden": false,
          "id": "autodate2082344108",
          "name": "created",
          "onCreate": true,
          "onUpdate": false,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "hidden": false,
          "id": "autodate0493873629",
          "name": "updated",
          "onCreate": true,
          "onUpdate": true,
          "presentable": false,
          "system": false,
          "type": "autodate"
        }
      ],
      "id": "pbc_2198534155",
      "indexes": [],
      "listRule": "@request.auth.id != ''",
      "name": "configuracion",
      "system": false,
      "type": "base",
      "updateRule": "@request.auth.role = 'Superadmin' || @request.auth.role = 'Administrador'",
      "viewRule": "@request.auth.id != ''"
    },
    {
      "createRule": "@request.auth.role = 'Superadmin' || @request.auth.role = 'Administrador'",
      "deleteRule": "@request.auth.role = 'Superadmin' || @request.auth.role = 'Administrador'",
      "fields": [
        {
          "autogeneratePattern": "[a-z0-9]{15}",
          "help": "",
          "hidden": false,
          "id": "text3208210256",
          "max": 15,
          "min": 15,
          "name": "id",
          "pattern": "^[a-z0-9]+$",
          "presentable": false,
          "primaryKey": true,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text982552870",
          "max": 0,
          "min": 0,
          "name": "nombre",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text2687119104",
          "max": 0,
          "min": 0,
          "name": "descripcion",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "hidden": false,
          "id": "autodate2990389176",
          "name": "created",
          "onCreate": true,
          "onUpdate": false,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "hidden": false,
          "id": "autodate3332085495",
          "name": "updated",
          "onCreate": true,
          "onUpdate": true,
          "presentable": false,
          "system": false,
          "type": "autodate"
        }
      ],
      "id": "pbc_8149243288",
      "indexes": [],
      "listRule": "",
      "name": "zonas_rutas",
      "system": false,
      "type": "base",
      "updateRule": "@request.auth.role = 'Superadmin' || @request.auth.role = 'Administrador'",
      "viewRule": ""
    },
    {
      "createRule": "@request.auth.id != ''",
      "deleteRule": "@request.auth.id != ''",
      "fields": [
        {
          "autogeneratePattern": "[a-z0-9]{15}",
          "help": "",
          "hidden": false,
          "id": "text3161840828",
          "max": 15,
          "min": 15,
          "name": "id",
          "pattern": "^[a-z0-9]+$",
          "presentable": false,
          "primaryKey": true,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "cascadeDelete": false,
          "collectionId": "pbc_8149243288",
          "help": "",
          "hidden": false,
          "id": "relation9396873044",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "zona_ruta",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "relation"
        },
        {
          "help": "",
          "hidden": false,
          "id": "date9407933401",
          "max": "",
          "min": "",
          "name": "fecha_actualizacion",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "date"
        },
        {
          "hidden": false,
          "id": "autodate0042130621",
          "name": "created",
          "onCreate": true,
          "onUpdate": false,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "hidden": false,
          "id": "autodate1723245364",
          "name": "updated",
          "onCreate": true,
          "onUpdate": true,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "help": "",
          "hidden": false,
          "id": "number3139177447",
          "max": null,
          "min": 0,
          "name": "costo",
          "onlyInt": false,
          "presentable": false,
          "required": true,
          "system": false,
          "type": "number"
        },
        {
          "help": "",
          "hidden": false,
          "id": "select2107839331",
          "maxSelect": 0,
          "name": "unidad_medida",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "select",
          "values": [
            "litro",
            "kilogramo"
          ]
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text3018340884",
          "max": 0,
          "min": 0,
          "name": "actualizado_por",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        }
      ],
      "id": "pbc_1890722555",
      "indexes": [],
      "listRule": "",
      "name": "costos_zonas",
      "system": false,
      "type": "base",
      "updateRule": "@request.auth.id != ''",
      "viewRule": ""
    },
    {
      "createRule": "@request.auth.id != ''",
      "deleteRule": "@request.auth.id != ''",
      "fields": [
        {
          "autogeneratePattern": "[a-z0-9]{15}",
          "help": "",
          "hidden": false,
          "id": "text3189843587",
          "max": 15,
          "min": 15,
          "name": "id",
          "pattern": "^[a-z0-9]+$",
          "presentable": false,
          "primaryKey": true,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text7665069400",
          "max": 0,
          "min": 0,
          "name": "razon_social",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text9133785093",
          "max": 0,
          "min": 0,
          "name": "direccion",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text8103894894",
          "max": 0,
          "min": 0,
          "name": "telefono",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "exceptDomains": [],
          "help": "",
          "hidden": false,
          "id": "email2046320526",
          "name": "email",
          "onlyDomains": [],
          "presentable": false,
          "required": false,
          "system": false,
          "type": "email"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text9550482671",
          "max": 0,
          "min": 0,
          "name": "observaciones",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "hidden": false,
          "id": "autodate4291493107",
          "name": "created",
          "onCreate": true,
          "onUpdate": false,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "hidden": false,
          "id": "autodate5380439375",
          "name": "updated",
          "onCreate": true,
          "onUpdate": true,
          "presentable": false,
          "system": false,
          "type": "autodate"
        }
      ],
      "id": "pbc_4082404368",
      "indexes": [],
      "listRule": "@request.auth.id != ''",
      "name": "proveedores",
      "system": false,
      "type": "base",
      "updateRule": "@request.auth.id != ''",
      "viewRule": "@request.auth.id != ''"
    },
    {
      "createRule": "@request.auth.role = 'Superadmin' || @request.auth.role = 'Administrador'",
      "deleteRule": "@request.auth.role = 'Superadmin'",
      "fields": [
        {
          "autogeneratePattern": "[a-z0-9]{15}",
          "help": "",
          "hidden": false,
          "id": "text4506239099",
          "max": 15,
          "min": 15,
          "name": "id",
          "pattern": "^[a-z0-9]+$",
          "presentable": false,
          "primaryKey": true,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text4769339334",
          "max": 0,
          "min": 0,
          "name": "nombre",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": false,
          "type": "text"
        },
        {
          "help": "",
          "hidden": false,
          "id": "select9570955383",
          "maxSelect": 1,
          "name": "ubicacion",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "select",
          "values": [
            "Header Principal",
            "Sección Dashboard"
          ]
        },
        {
          "help": "",
          "hidden": false,
          "id": "bool8755448544",
          "name": "estado",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "bool"
        },
        {
          "help": "",
          "hidden": false,
          "id": "number9898489294",
          "max": null,
          "min": 1,
          "name": "orden",
          "onlyInt": false,
          "presentable": false,
          "required": true,
          "system": false,
          "type": "number"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text4425107019",
          "max": 0,
          "min": 0,
          "name": "icono",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "help": "",
          "hidden": false,
          "id": "json3703544424",
          "maxSize": 0,
          "name": "roles_permitidos",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "json"
        },
        {
          "hidden": false,
          "id": "autodate4609803311",
          "name": "created",
          "onCreate": true,
          "onUpdate": false,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "hidden": false,
          "id": "autodate2217949604",
          "name": "updated",
          "onCreate": true,
          "onUpdate": true,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "help": "",
          "hidden": false,
          "id": "json4036444908",
          "maxSize": 0,
          "name": "colecciones",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "json"
        }
      ],
      "id": "pbc_4981314215",
      "indexes": [
        "CREATE UNIQUE INDEX idx_modulos_config_nombre ON modulos_config (nombre)",
        "CREATE UNIQUE INDEX idx_modulos_config_orden ON modulos_config (orden)"
      ],
      "listRule": "@request.auth.id != ''",
      "name": "modulos_config",
      "system": false,
      "type": "base",
      "updateRule": "@request.auth.role = 'Superadmin' || @request.auth.role = 'Administrador'",
      "viewRule": "@request.auth.id != ''"
    },
    {
      "createRule": "@request.auth.role = 'Superadmin' || @request.auth.role = 'Administrador'",
      "deleteRule": "@request.auth.role = 'Superadmin'",
      "fields": [
        {
          "autogeneratePattern": "[a-z0-9]{15}",
          "help": "",
          "hidden": false,
          "id": "text7698406830",
          "max": 15,
          "min": 15,
          "name": "id",
          "pattern": "^[a-z0-9]+$",
          "presentable": false,
          "primaryKey": true,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "help": "",
          "hidden": false,
          "id": "select3468672057",
          "maxSelect": 1,
          "name": "tipo",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "select",
          "values": [
            "header",
            "login",
            "dashboard",
            "favicon"
          ]
        },
        {
          "help": "",
          "hidden": false,
          "id": "file2953803309",
          "maxSelect": 1,
          "maxSize": 5242880,
          "mimeTypes": [
            "image/png",
            "image/jpeg",
            "image/svg+xml"
          ],
          "name": "archivo",
          "presentable": false,
          "protected": false,
          "required": false,
          "system": false,
          "thumbs": [],
          "type": "file"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text5863201830",
          "max": 0,
          "min": 0,
          "name": "url_default",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "hidden": false,
          "id": "autodate3137535410",
          "name": "fecha_actualizacion",
          "onCreate": true,
          "onUpdate": true,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "hidden": false,
          "id": "autodate2245942600",
          "name": "created",
          "onCreate": true,
          "onUpdate": false,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "hidden": false,
          "id": "autodate0832415438",
          "name": "updated",
          "onCreate": true,
          "onUpdate": true,
          "presentable": false,
          "system": false,
          "type": "autodate"
        }
      ],
      "id": "pbc_4192986477",
      "indexes": [],
      "listRule": "@request.auth.id != ''",
      "name": "logotipos",
      "system": false,
      "type": "base",
      "updateRule": "@request.auth.role = 'Superadmin' || @request.auth.role = 'Administrador'",
      "viewRule": "@request.auth.id != ''"
    },
    {
      "createRule": "@request.auth.role = 'Superadmin' || @request.auth.role = 'Administrador'",
      "deleteRule": "@request.auth.role = 'Superadmin'",
      "fields": [
        {
          "autogeneratePattern": "[a-z0-9]{15}",
          "help": "",
          "hidden": false,
          "id": "text1065521905",
          "max": 15,
          "min": 15,
          "name": "id",
          "pattern": "^[a-z0-9]+$",
          "presentable": false,
          "primaryKey": true,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text9675846717",
          "max": 0,
          "min": 0,
          "name": "marca",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text9689199059",
          "max": 0,
          "min": 0,
          "name": "modelo",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": false,
          "type": "text"
        },
        {
          "help": "",
          "hidden": false,
          "id": "date8668546019",
          "max": "",
          "min": "",
          "name": "fecha_calibracion",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "date"
        },
        {
          "help": "",
          "hidden": false,
          "id": "number6782494160",
          "max": null,
          "min": 0,
          "name": "vi_actual",
          "onlyInt": false,
          "presentable": false,
          "required": true,
          "system": false,
          "type": "number"
        },
        {
          "help": "",
          "hidden": false,
          "id": "date6592556683",
          "max": "",
          "min": "",
          "name": "fecha_vi",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "date"
        },
        {
          "help": "",
          "hidden": false,
          "id": "select7108039437",
          "maxSelect": 1,
          "name": "estado",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "select",
          "values": [
            "activo",
            "inactivo"
          ]
        },
        {
          "hidden": false,
          "id": "autodate6152021186",
          "name": "created",
          "onCreate": true,
          "onUpdate": false,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "hidden": false,
          "id": "autodate2446186633",
          "name": "updated",
          "onCreate": true,
          "onUpdate": true,
          "presentable": false,
          "system": false,
          "type": "autodate"
        }
      ],
      "id": "pbc_4997444020",
      "indexes": [],
      "listRule": "@request.auth.role = 'Superadmin' || @request.auth.role = 'Administrador'",
      "name": "drv",
      "system": false,
      "type": "base",
      "updateRule": "@request.auth.role = 'Superadmin' || @request.auth.role = 'Administrador'",
      "viewRule": "@request.auth.role = 'Superadmin' || @request.auth.role = 'Administrador'"
    },
    {
      "createRule": "@request.auth.role = 'Superadmin' || @request.auth.role = 'Administrador'",
      "deleteRule": "@request.auth.role = 'Superadmin'",
      "fields": [
        {
          "autogeneratePattern": "[a-z0-9]{15}",
          "help": "",
          "hidden": false,
          "id": "text3944104140",
          "max": 15,
          "min": 15,
          "name": "id",
          "pattern": "^[a-z0-9]+$",
          "presentable": false,
          "primaryKey": true,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "cascadeDelete": false,
          "collectionId": "pbc_4997444020",
          "help": "",
          "hidden": false,
          "id": "relation1828045463",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "drv_id",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "relation"
        },
        {
          "help": "",
          "hidden": false,
          "id": "number4839306617",
          "max": null,
          "min": 0,
          "name": "vi",
          "onlyInt": false,
          "presentable": false,
          "required": true,
          "system": false,
          "type": "number"
        },
        {
          "help": "",
          "hidden": false,
          "id": "number2276785691",
          "max": null,
          "min": 0,
          "name": "vf",
          "onlyInt": false,
          "presentable": false,
          "required": true,
          "system": false,
          "type": "number"
        },
        {
          "help": "",
          "hidden": false,
          "id": "number4652850590",
          "max": null,
          "min": 0,
          "name": "corte",
          "onlyInt": false,
          "presentable": false,
          "required": true,
          "system": false,
          "type": "number"
        },
        {
          "help": "",
          "hidden": false,
          "id": "date0541704746",
          "max": "",
          "min": "",
          "name": "fecha_hora_vi",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "date"
        },
        {
          "help": "",
          "hidden": false,
          "id": "date5679516578",
          "max": "",
          "min": "",
          "name": "fecha_hora_vf",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "date"
        },
        {
          "cascadeDelete": false,
          "collectionId": "pbc_1736455494",
          "help": "",
          "hidden": false,
          "id": "relation0953413805",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "usuario",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "relation"
        },
        {
          "hidden": false,
          "id": "autodate7420626648",
          "name": "fecha_creacion",
          "onCreate": true,
          "onUpdate": false,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "hidden": false,
          "id": "autodate3508727455",
          "name": "created",
          "onCreate": true,
          "onUpdate": false,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "hidden": false,
          "id": "autodate9703402402",
          "name": "updated",
          "onCreate": true,
          "onUpdate": true,
          "presentable": false,
          "system": false,
          "type": "autodate"
        }
      ],
      "id": "pbc_5977182499",
      "indexes": [],
      "listRule": "@request.auth.role = 'Superadmin' || @request.auth.role = 'Administrador'",
      "name": "drv_cortes",
      "system": false,
      "type": "base",
      "updateRule": "@request.auth.role = 'Superadmin' || @request.auth.role = 'Administrador' || usuario = @request.auth.id",
      "viewRule": "@request.auth.role = 'Superadmin' || @request.auth.role = 'Administrador'"
    },
    {
      "createRule": "@request.auth.role = 'Superadmin' || @request.auth.role = 'Administrador'",
      "deleteRule": "@request.auth.role = 'Superadmin'",
      "fields": [
        {
          "autogeneratePattern": "[a-z0-9]{15}",
          "help": "",
          "hidden": false,
          "id": "text3684283910",
          "max": 15,
          "min": 15,
          "name": "id",
          "pattern": "^[a-z0-9]+$",
          "presentable": false,
          "primaryKey": true,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text2955889637",
          "max": 0,
          "min": 0,
          "name": "nombre",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": false,
          "type": "text"
        },
        {
          "help": "",
          "hidden": false,
          "id": "select6663152006",
          "maxSelect": 1,
          "name": "rol",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "select",
          "values": [
            "PLANTA",
            "DE CARBURACIÓN"
          ]
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text6897872021",
          "max": 0,
          "min": 0,
          "name": "calle",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text6998837185",
          "max": 0,
          "min": 0,
          "name": "numero",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text8651852498",
          "max": 0,
          "min": 0,
          "name": "colonia",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text3199243681",
          "max": 0,
          "min": 0,
          "name": "municipio",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text4046579571",
          "max": 0,
          "min": 0,
          "name": "estado",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text2885657522",
          "max": 0,
          "min": 0,
          "name": "telefono",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "cascadeDelete": false,
          "collectionId": "pbc_1736455494",
          "help": "",
          "hidden": false,
          "id": "relation7893723375",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "responsable_id",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "relation"
        },
        {
          "cascadeDelete": false,
          "collectionId": "pbc_1736455494",
          "help": "",
          "hidden": false,
          "id": "relation9530658918",
          "maxSelect": 0,
          "minSelect": 0,
          "name": "colaboradores",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "relation"
        },
        {
          "help": "",
          "hidden": false,
          "id": "select5900852935",
          "maxSelect": 1,
          "name": "estado_estacion",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "select",
          "values": [
            "activa",
            "inactiva"
          ]
        },
        {
          "hidden": false,
          "id": "autodate7543045970",
          "name": "fecha_creacion",
          "onCreate": true,
          "onUpdate": false,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "cascadeDelete": false,
          "collectionId": "pbc_1736455494",
          "help": "",
          "hidden": false,
          "id": "relation1708200895",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "usuario_creacion",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "relation"
        },
        {
          "hidden": false,
          "id": "autodate0917885072",
          "name": "created",
          "onCreate": true,
          "onUpdate": false,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "hidden": false,
          "id": "autodate8855684457",
          "name": "updated",
          "onCreate": true,
          "onUpdate": true,
          "presentable": false,
          "system": false,
          "type": "autodate"
        }
      ],
      "id": "pbc_5649188167",
      "indexes": [],
      "listRule": "",
      "name": "estaciones",
      "system": false,
      "type": "base",
      "updateRule": "@request.auth.role = 'Superadmin' || @request.auth.role = 'Administrador'",
      "viewRule": ""
    },
    {
      "createRule": "@request.auth.id != ''",
      "deleteRule": "@request.auth.role = 'Superadmin' || @request.auth.role = 'Administrador'",
      "fields": [
        {
          "autogeneratePattern": "[a-z0-9]{15}",
          "help": "",
          "hidden": false,
          "id": "text7306316371",
          "max": 15,
          "min": 15,
          "name": "id",
          "pattern": "^[a-z0-9]+$",
          "presentable": false,
          "primaryKey": true,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "cascadeDelete": false,
          "collectionId": "pbc_5649188167",
          "help": "",
          "hidden": false,
          "id": "relation9998614381",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "estacion_id",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "relation"
        },
        {
          "cascadeDelete": false,
          "collectionId": "pbc_4997444020",
          "help": "",
          "hidden": false,
          "id": "relation4980468855",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "drv_id",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "relation"
        },
        {
          "hidden": false,
          "id": "autodate0338428475",
          "name": "fecha_asociacion",
          "onCreate": true,
          "onUpdate": false,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "hidden": false,
          "id": "autodate9205319615",
          "name": "created",
          "onCreate": true,
          "onUpdate": false,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "hidden": false,
          "id": "autodate8657057835",
          "name": "updated",
          "onCreate": true,
          "onUpdate": true,
          "presentable": false,
          "system": false,
          "type": "autodate"
        }
      ],
      "id": "pbc_6486165234",
      "indexes": [
        "CREATE UNIQUE INDEX idx_estacion_drv_unique ON estacion_drv (estacion_id, drv_id)"
      ],
      "listRule": "@request.auth.id != ''",
      "name": "estacion_drv",
      "system": false,
      "type": "base",
      "updateRule": null,
      "viewRule": "@request.auth.id != ''"
    },
    {
      "createRule": "@request.auth.role = 'Superadmin' || @request.auth.role = 'Administrador'",
      "deleteRule": "@request.auth.role = 'Superadmin' || @request.auth.role = 'Administrador'",
      "fields": [
        {
          "autogeneratePattern": "[a-z0-9]{15}",
          "help": "",
          "hidden": false,
          "id": "text9401203035",
          "max": 15,
          "min": 15,
          "name": "id",
          "pattern": "^[a-z0-9]+$",
          "presentable": false,
          "primaryKey": true,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text2587150956",
          "max": 0,
          "min": 0,
          "name": "numero_tanque",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": true,
          "system": false,
          "type": "text"
        },
        {
          "help": "",
          "hidden": false,
          "id": "number3454780516",
          "max": null,
          "min": 1,
          "name": "capacidad_total",
          "onlyInt": false,
          "presentable": false,
          "required": true,
          "system": false,
          "type": "number"
        },
        {
          "help": "",
          "hidden": false,
          "id": "number6422684969",
          "max": null,
          "min": null,
          "name": "capacidad_permitida",
          "onlyInt": false,
          "presentable": false,
          "required": false,
          "system": false,
          "type": "number"
        },
        {
          "help": "",
          "hidden": false,
          "id": "number2190283051",
          "max": null,
          "min": null,
          "name": "carga_disponible_inicial",
          "onlyInt": false,
          "presentable": false,
          "required": false,
          "system": false,
          "type": "number"
        },
        {
          "help": "",
          "hidden": false,
          "id": "number2110956785",
          "max": null,
          "min": null,
          "name": "carga_disponible_litros",
          "onlyInt": false,
          "presentable": false,
          "required": false,
          "system": false,
          "type": "number"
        },
        {
          "help": "",
          "hidden": false,
          "id": "number7801976886",
          "max": null,
          "min": null,
          "name": "carga_faltante",
          "onlyInt": false,
          "presentable": false,
          "required": false,
          "system": false,
          "type": "number"
        },
        {
          "help": "",
          "hidden": false,
          "id": "select3659408177",
          "maxSelect": 1,
          "name": "estado",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "select",
          "values": [
            "Activo",
            "Desactivado",
            "Mantenimiento"
          ]
        },
        {
          "help": "",
          "hidden": false,
          "id": "number0760345876",
          "max": null,
          "min": null,
          "name": "temperatura",
          "onlyInt": false,
          "presentable": false,
          "required": false,
          "system": false,
          "type": "number"
        },
        {
          "help": "",
          "hidden": false,
          "id": "file1510006174",
          "maxSelect": 1,
          "maxSize": 20971520,
          "mimeTypes": [
            "image/jpeg",
            "image/png"
          ],
          "name": "imagen_lectura_a",
          "presentable": false,
          "protected": false,
          "required": false,
          "system": false,
          "thumbs": [],
          "type": "file"
        },
        {
          "cascadeDelete": false,
          "collectionId": "pbc_4997444020",
          "help": "",
          "hidden": false,
          "id": "relation8684762471",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "drv_id",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "relation"
        },
        {
          "help": "",
          "hidden": false,
          "id": "select3627860635",
          "maxSelect": 1,
          "name": "origen_carga",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "select",
          "values": [
            "Proveedor",
            "Planta"
          ]
        },
        {
          "cascadeDelete": false,
          "collectionId": "pbc_4082404368",
          "help": "",
          "hidden": false,
          "id": "relation7790228742",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "proveedor_id",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "relation"
        },
        {
          "cascadeDelete": false,
          "collectionId": "pbc_5649188167",
          "help": "",
          "hidden": false,
          "id": "relation5635427762",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "estacion_id",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "relation"
        },
        {
          "help": "",
          "hidden": false,
          "id": "bool6706428635",
          "name": "notificacion_activa",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "bool"
        },
        {
          "help": "",
          "hidden": false,
          "id": "date1891320396",
          "max": "",
          "min": "",
          "name": "fecha_notificacion",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "date"
        },
        {
          "cascadeDelete": false,
          "collectionId": "pbc_1736455494",
          "help": "",
          "hidden": false,
          "id": "relation5373715405",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "usuario_creacion",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "relation"
        },
        {
          "hidden": false,
          "id": "autodate5720738423",
          "name": "created",
          "onCreate": true,
          "onUpdate": false,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "hidden": false,
          "id": "autodate4864683896",
          "name": "updated",
          "onCreate": true,
          "onUpdate": true,
          "presentable": false,
          "system": false,
          "type": "autodate"
        }
      ],
      "id": "pbc_6053979442",
      "indexes": [],
      "listRule": "@request.auth.role = 'Superadmin' || @request.auth.role = 'Administrador'",
      "name": "tanques_carga",
      "system": false,
      "type": "base",
      "updateRule": "@request.auth.role = 'Superadmin' || @request.auth.role = 'Administrador'",
      "viewRule": "@request.auth.role = 'Superadmin' || @request.auth.role = 'Administrador'"
    },
    {
      "createRule": "@request.auth.role = 'Superadmin' || @request.auth.role = 'Administrador'",
      "deleteRule": "@request.auth.role = 'Superadmin' || @request.auth.role = 'Administrador'",
      "fields": [
        {
          "autogeneratePattern": "[a-z0-9]{15}",
          "help": "",
          "hidden": false,
          "id": "text7625949910",
          "max": 15,
          "min": 15,
          "name": "id",
          "pattern": "^[a-z0-9]+$",
          "presentable": false,
          "primaryKey": true,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "cascadeDelete": false,
          "collectionId": "pbc_6053979442",
          "help": "",
          "hidden": false,
          "id": "relation7352785519",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "tanque_id",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "relation"
        },
        {
          "help": "",
          "hidden": false,
          "id": "select2129392291",
          "maxSelect": 1,
          "name": "tipo_lectura",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "select",
          "values": [
            "Lectura A",
            "Lectura B"
          ]
        },
        {
          "help": "",
          "hidden": false,
          "id": "number6198045735",
          "max": 100,
          "min": 0,
          "name": "carga_disponible_porcentaje",
          "onlyInt": false,
          "presentable": false,
          "required": true,
          "system": false,
          "type": "number"
        },
        {
          "help": "",
          "hidden": false,
          "id": "number2363873939",
          "max": null,
          "min": null,
          "name": "carga_disponible_litros",
          "onlyInt": false,
          "presentable": false,
          "required": false,
          "system": false,
          "type": "number"
        },
        {
          "help": "",
          "hidden": false,
          "id": "number7453925228",
          "max": null,
          "min": null,
          "name": "carga_faltante",
          "onlyInt": false,
          "presentable": false,
          "required": false,
          "system": false,
          "type": "number"
        },
        {
          "help": "",
          "hidden": false,
          "id": "number5293332206",
          "max": null,
          "min": null,
          "name": "temperatura",
          "onlyInt": false,
          "presentable": false,
          "required": true,
          "system": false,
          "type": "number"
        },
        {
          "help": "",
          "hidden": false,
          "id": "file4268028188",
          "maxSelect": 1,
          "maxSize": 20971520,
          "mimeTypes": [
            "image/jpeg",
            "image/png"
          ],
          "name": "imagen_evidencia",
          "presentable": false,
          "protected": false,
          "required": false,
          "system": false,
          "thumbs": [],
          "type": "file"
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text0891601093",
          "max": 0,
          "min": 0,
          "name": "observaciones",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "cascadeDelete": false,
          "collectionId": "pbc_1736455494",
          "help": "",
          "hidden": false,
          "id": "relation5584614631",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "usuario_lectura",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "relation"
        },
        {
          "hidden": false,
          "id": "autodate4291627526",
          "name": "created",
          "onCreate": true,
          "onUpdate": false,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "hidden": false,
          "id": "autodate5290849665",
          "name": "updated",
          "onCreate": true,
          "onUpdate": true,
          "presentable": false,
          "system": false,
          "type": "autodate"
        }
      ],
      "id": "pbc_1336445091",
      "indexes": [],
      "listRule": "@request.auth.role = 'Superadmin' || @request.auth.role = 'Administrador'",
      "name": "lecturas_carga",
      "system": false,
      "type": "base",
      "updateRule": "@request.auth.role = 'Superadmin' || @request.auth.role = 'Administrador'",
      "viewRule": "@request.auth.role = 'Superadmin' || @request.auth.role = 'Administrador'"
    },
    {
      "createRule": "@request.auth.role = 'Superadmin' || @request.auth.role = 'Administrador'",
      "deleteRule": "@request.auth.role = 'Superadmin' || @request.auth.role = 'Administrador'",
      "fields": [
        {
          "autogeneratePattern": "[a-z0-9]{15}",
          "help": "",
          "hidden": false,
          "id": "text4811973522",
          "max": 15,
          "min": 15,
          "name": "id",
          "pattern": "^[a-z0-9]+$",
          "presentable": false,
          "primaryKey": true,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "cascadeDelete": false,
          "collectionId": "pbc_6053979442",
          "help": "",
          "hidden": false,
          "id": "relation3516684733",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "tanque_id",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "relation"
        },
        {
          "cascadeDelete": false,
          "collectionId": "pbc_4997444020",
          "help": "",
          "hidden": false,
          "id": "relation7701708543",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "drv_id",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "relation"
        },
        {
          "help": "",
          "hidden": false,
          "id": "number2704078083",
          "max": null,
          "min": null,
          "name": "ultimo_corte_drv",
          "onlyInt": false,
          "presentable": false,
          "required": false,
          "system": false,
          "type": "number"
        },
        {
          "help": "",
          "hidden": false,
          "id": "select9932935666",
          "maxSelect": 1,
          "name": "autorizacion_carga_tipo",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "select",
          "values": [
            "Porcentaje",
            "Litros"
          ]
        },
        {
          "help": "",
          "hidden": false,
          "id": "number7925160877",
          "max": null,
          "min": null,
          "name": "autorizacion_carga_valor",
          "onlyInt": false,
          "presentable": false,
          "required": true,
          "system": false,
          "type": "number"
        },
        {
          "help": "",
          "hidden": false,
          "id": "number4863628411",
          "max": null,
          "min": null,
          "name": "carga_inicial_porcentaje",
          "onlyInt": false,
          "presentable": false,
          "required": true,
          "system": false,
          "type": "number"
        },
        {
          "help": "",
          "hidden": false,
          "id": "number6816273298",
          "max": null,
          "min": null,
          "name": "carga_final_porcentaje",
          "onlyInt": false,
          "presentable": false,
          "required": true,
          "system": false,
          "type": "number"
        },
        {
          "help": "",
          "hidden": false,
          "id": "number6725861373",
          "max": null,
          "min": null,
          "name": "carga_disponible_litros_final",
          "onlyInt": false,
          "presentable": false,
          "required": false,
          "system": false,
          "type": "number"
        },
        {
          "help": "",
          "hidden": false,
          "id": "number5879789285",
          "max": null,
          "min": null,
          "name": "carga_faltante_final",
          "onlyInt": false,
          "presentable": false,
          "required": false,
          "system": false,
          "type": "number"
        },
        {
          "help": "",
          "hidden": false,
          "id": "number7663678677",
          "max": null,
          "min": null,
          "name": "temperatura_final",
          "onlyInt": false,
          "presentable": false,
          "required": false,
          "system": false,
          "type": "number"
        },
        {
          "help": "",
          "hidden": false,
          "id": "file0866246969",
          "maxSelect": 1,
          "maxSize": 20971520,
          "mimeTypes": [
            "image/jpeg",
            "image/png"
          ],
          "name": "imagen_lectura_b",
          "presentable": false,
          "protected": false,
          "required": false,
          "system": false,
          "thumbs": [],
          "type": "file"
        },
        {
          "help": "",
          "hidden": false,
          "id": "select6177213697",
          "maxSelect": 1,
          "name": "estado_corte",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "select",
          "values": [
            "Pendiente",
            "Autorizado",
            "Completado"
          ]
        },
        {
          "autogeneratePattern": "",
          "help": "",
          "hidden": false,
          "id": "text9413393386",
          "max": 0,
          "min": 0,
          "name": "observaciones",
          "pattern": "",
          "presentable": false,
          "primaryKey": false,
          "required": false,
          "system": false,
          "type": "text"
        },
        {
          "cascadeDelete": false,
          "collectionId": "pbc_1736455494",
          "help": "",
          "hidden": false,
          "id": "relation6173212791",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "usuario_corte",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "relation"
        },
        {
          "hidden": false,
          "id": "autodate3480481217",
          "name": "created",
          "onCreate": true,
          "onUpdate": false,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "hidden": false,
          "id": "autodate8960523014",
          "name": "updated",
          "onCreate": true,
          "onUpdate": true,
          "presentable": false,
          "system": false,
          "type": "autodate"
        }
      ],
      "id": "pbc_4877992357",
      "indexes": [],
      "listRule": "@request.auth.role = 'Superadmin' || @request.auth.role = 'Administrador'",
      "name": "cortes_carga",
      "system": false,
      "type": "base",
      "updateRule": "@request.auth.role = 'Superadmin' || @request.auth.role = 'Administrador'",
      "viewRule": "@request.auth.role = 'Superadmin' || @request.auth.role = 'Administrador'"
    },
    {
      "createRule": "@request.auth.role = 'Superadmin' || @request.auth.role = 'Administrador'",
      "deleteRule": "@request.auth.role = 'Superadmin'",
      "fields": [
        {
          "autogeneratePattern": "[a-z0-9]{15}",
          "help": "",
          "hidden": false,
          "id": "text3510460338",
          "max": 15,
          "min": 15,
          "name": "id",
          "pattern": "^[a-z0-9]+$",
          "presentable": false,
          "primaryKey": true,
          "required": true,
          "system": true,
          "type": "text"
        },
        {
          "cascadeDelete": false,
          "collectionId": "pbc_4997444020",
          "help": "",
          "hidden": false,
          "id": "relation8059611749",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "drv_id",
          "presentable": false,
          "required": true,
          "system": false,
          "type": "relation"
        },
        {
          "help": "",
          "hidden": false,
          "id": "number9297286218",
          "max": null,
          "min": null,
          "name": "corte_numero",
          "onlyInt": false,
          "presentable": false,
          "required": true,
          "system": false,
          "type": "number"
        },
        {
          "help": "",
          "hidden": false,
          "id": "date6898572182",
          "max": "",
          "min": "",
          "name": "fecha_corte",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "date"
        },
        {
          "help": "",
          "hidden": false,
          "id": "number3283318594",
          "max": null,
          "min": null,
          "name": "valor_corte",
          "onlyInt": false,
          "presentable": false,
          "required": false,
          "system": false,
          "type": "number"
        },
        {
          "cascadeDelete": false,
          "collectionId": "pbc_6053979442",
          "help": "",
          "hidden": false,
          "id": "relation1943597855",
          "maxSelect": 1,
          "minSelect": 0,
          "name": "tanque_id",
          "presentable": false,
          "required": false,
          "system": false,
          "type": "relation"
        },
        {
          "hidden": false,
          "id": "autodate7312057581",
          "name": "created",
          "onCreate": true,
          "onUpdate": false,
          "presentable": false,
          "system": false,
          "type": "autodate"
        },
        {
          "hidden": false,
          "id": "autodate7793369014",
          "name": "updated",
          "onCreate": true,
          "onUpdate": true,
          "presentable": false,
          "system": false,
          "type": "autodate"
        }
      ],
      "id": "pbc_2946180095",
      "indexes": [],
      "listRule": "@request.auth.role = 'Superadmin' || @request.auth.role = 'Administrador'",
      "name": "historial_cortes_drv",
      "system": false,
      "type": "base",
      "updateRule": null,
      "viewRule": "@request.auth.role = 'Superadmin' || @request.auth.role = 'Administrador'"
    }
  ];

  return app.importCollections(snapshot, true);
}, (app) => {
  return null;
})